In [4]:
####NOTES
#Date range:  jan1 2018 until Dec 31 2018
#daily
#USDT_BTC -- 86400

In [5]:
from poloniex import Poloniex
polo = Poloniex()
help(polo)

Help on Poloniex in module poloniex.poloniex object:

class Poloniex(PoloniexPublic)
 |  Client to connect to Poloniex private APIs.
 |
 |  Method resolution order:
 |      Poloniex
 |      PoloniexPublic
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, apikey=None, secret=None, public_url='https://poloniex.com/public', private_url='https://poloniex.com/tradingApi', limit=6, session_class=<class 'requests.sessions.Session'>, session=None, startup_lock=None, semaphore=None, timer=None, nonce_iter=None, nonce_lock=None)
 |      Initialize the Poloniex private client.
 |
 |  buy(self, currencyPair, rate, amount, fillOrKill=None, immediateOrCancel=None, postOnly=None)
 |      Places a limit buy order in a given market. Required POST parameters
 |      are "currencyPair", "rate", and "amount". If successful, the method
 |      will return the order number.
 |      You may optionally set "fillOrKill", "immediateOrCancel", "postOnly"
 |      to 1. A fill-or-kill order will either fill in its entirety or be
 |      completely aborted. An immediate-or-cancel order can be partially or
 |      completely filled, but any portion of the order that cannot be filled
 |      immediately will be canceled rather than left on the order book.
 |      A post-only order will only be placed if no portion of it fills
 |      immediately; this guarantees you will never pay the taker fee on any
 |      part of the order that fills.
 |
 |  cancelLoanOffer(self, orderNumber)
 |      Cancels a loan offer specified by the "orderNumber" POST
 |      parameter.
 |
 |  cancelOrder(self, orderNumber)
 |      Cancels an order you have placed in a given market. Required POST
 |      parameter is "orderNumber".
 |
 |  closeMarginPosition(self, currencyPair)
 |      Closes your margin position in a given market (specified by the
 |      "currencyPair" POST parameter) using a market order. This call will
 |      also return success if you do not have an open position in the
 |      specified market.
 |
 |  createLoanOffer(self, currency, amount, duration, autoRenew, lendingRate)
 |      Creates a loan offer for a given currency. Required POST parameters
 |      are "currency", "amount", "duration", "autoRenew" (0 or 1), and
 |      "lendingRate".
 |
 |  generateNewAddress(self, currency)
 |      Generates a new deposit address for the currency specified by the
 |      "currency" POST parameter. Only one address per currency per day may be
 |      generated, and a new address may not be generated before the
 |      previously-generated one has been used.
 |
 |  getMarginPosition(self, currencyPair)
 |      Returns information about your margin position in a given market,
 |      specified by the "currencyPair" POST parameter. You may set
 |      "currencyPair" to "all" if you wish to fetch all of your margin
 |      positions at once. If you have no margin position in the specified
 |      market, "type" will be set to "none". "liquidationPrice" is an
 |      estimate, and does not necessarily represent the price at which an
 |      actual forced liquidation will occur. If you have no liquidation
 |      price, the value will be -1.
 |
 |  marginBuy(self, currencyPair, rate, amount, lendingRate=None)
 |      Places a margin buy order in a given market. Required POST
 |      parameters are "currencyPair", "rate", and "amount". You may optionally
 |       specify a maximum lending rate using the "lendingRate" parameter.
 |       If successful, the method will return the order number and any trades
 |       immediately resulting from your order.
 |
 |  marginSell(self, currencyPair, rate, amount, lendingRate=None)
 |      Places a margin sell order in a given market. Parameters and output
 |      are the same as for the marginBuy method.
 |
 |  moveOrder(self, orderNumber, rate, amount=None, postOnly=None, immediateOrCancel=None)
 |      Cancels an order and places a new one of the same type in a single
 |      atomic transaction, meaning either both operations will succeed or both
 |       will fail. Required POST parameters are "orderNumber" and "rate"; you
 |       may optionally specify "amount" if you wish to change the amount of
 |       the new order. "postOnly" or "immediateOrCancel" may be specified for
 |       exchange orders, but will have no effect on margin orders.
 |
 |  returnActiveLoans(self)
 |      Returns your active loans for each currency.
 |
 |  returnAvailableAccountBalances(self, account=None)
 |      Returns your balances sorted by account. You may optionally specify
 |      the "account" POST parameter if you wish to fetch only the balances of
 |      one account. Please note that balances in your margin account may not
 |      be accessible if you have any open margin positions or orders.
 |
 |  returnBalances(self)
 |      Returns all of your available balances.
 |
 |  returnCompleteBalances(self, account=None)
 |      Returns all of your balances, including available balance, balance
 |      on orders, and the estimated BTC value of your balance. By default,
 |      this call is limited to your exchange account; set the "account" POST
 |      parameter to "all" to include your margin and lending accounts.
 |
 |  returnDepositAddresses(self)
 |      Returns all of your deposit addresses.
 |
 |  returnDeposits(self, start=0, end=4294967295)
 |      Returns your deposit history within a range, specified by the
 |      "start" and "end" POST parameters, both of which should be given as
 |      UNIX timestamps.
 |
 |  returnDepositsWithdrawals(self, start=0, end=4294967295)
 |      Returns your deposit and withdrawal history within a range,
 |      specified by the "start" and "end" POST parameters, both of which
 |      should be given as UNIX timestamps.
 |
 |  returnFeeInfo(self)
 |      If you are enrolled in the maker-taker fee schedule, returns your
 |      current trading fees and trailing 30-day volume in BTC. This
 |      information is updated once every 24 hours.
 |
 |  returnLendingHistory(self, start=0, end=4294967295, limit=None)
 |      Returns your lending history within a time range specified by the
 |      "start" and "end" POST parameters as UNIX timestamps. "limit" may also
 |      be specified to limit the number of rows returned.
 |
 |  returnMarginAccountSummary(self)
 |      Returns a summary of your entire margin account. This is the same
 |      information you will find in the Margin Account section of the Margin
 |      Trading page, under the Markets list.
 |
 |  returnOpenLoanOffers(self)
 |      Returns your open loan offers for each currency.
 |
 |  returnOpenOrders(self, currencyPair='all')
 |      Returns your open orders for a given market, specified by the
 |      "currencyPair" POST parameter, e.g. "BTC_XCP". Set "currencyPair" to
 |      "all" to return open orders for all markets.
 |
 |  returnOrderTrades(self, orderNumber)
 |      Returns all trades involving a given order, specified by the
 |      "orderNumber" POST parameter. If no trades for the order have occurred
 |      or you specify an order that does not belong to you, you will receive
 |      an error.
 |
 |  returnTradableBalances(self)
 |      Returns your current tradable balances for each currency in each
 |      market for which margin trading is enabled. Please note that these
 |      balances may vary continually with market conditions.
 |
 |  returnTradeHistory(self, currencyPair='all', start=None, end=None, limit=500)
 |      Returns your trade history for a given market, specified by the
 |      "currencyPair" POST parameter. You may specify "all" as the
 |      currencyPair to receive your trade history for all markets. You may
 |      optionally specify a range via "start" and/or "end" POST parameters,
 |      given in UNIX timestamp format; if you do not specify a range, it will
 |      be limited to one day.
 |
 |  returnTradeHistoryPublic(self, currencyPair, start=None, end=None)
 |      Returns the past 200 trades for a given market, or up to 50,000
 |      trades between a range specified in UNIX timestamps by the "start"
 |      and "end" GET parameters.
 |
 |  returnWithdrawals(self, start=0, end=4294967295)
 |      Returns your withdrawal history within a range, specified by the
 |      "start" and "end" POST parameters, both of which should be given as
 |      UNIX timestamps.
 |
 |  sell(self, currencyPair, rate, amount, fillOrKill=None, immediateOrCancel=None, postOnly=None)
 |      Places a sell order in a given market. Parameters and output are
 |      the same as for the buy method.
 |
 |  toggleAutoRenew(self, orderNumber)
 |      Toggles the autoRenew setting on an active loan, specified by the
 |      "orderNumber" POST parameter. If successful, "message" will indicate
 |      the new autoRenew setting.
 |
 |  transferBalance(self, currency, amount, fromAccount, toAccount)
 |      Transfers funds from one account to another (e.g. from your exchange
 |      account to your margin account). Required POST parameters are
 |      "currency", "amount", "fromAccount", and "toAccount".
 |
 |  withdraw(self, currency, amount, address, paymentId=None)
 |      Immediately places a withdrawal for a given currency, with no email
 |      confirmation. In order to use this method, the withdrawal privilege
 |      must be enabled for your API key. Required POST parameters are
 |      "currency", "amount", and "address". For XMR withdrawals, you may
 |      optionally specify "paymentId".
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from PoloniexPublic:
 |
 |  __del__(self)
 |
 |  return24hVolume(self)
 |      Returns the 24-hour volume for all markets, plus totals for
 |      primary currencies.
 |
 |  returnChartData(self, currencyPair, period, start=0, end=4294967295)
 |      Returns candlestick chart data. Required GET parameters are
 |      "currencyPair", "period" (candlestick period in seconds; valid values
 |      are 300, 900, 1800, 7200, 14400, and 86400), "start", and "end".
 |      "Start" and "end" are given in UNIX timestamp format and used to
 |      specify the date range for the data returned.
 |
 |  returnCurrencies(self)
 |      Returns information about currencies.
 |
 |  returnLoanOrders(self, currency)
 |      Returns the list of loan offers and demands for a given currency,
 |      specified by the "currency" GET parameter.
 |
 |  returnOrderBook(self, currencyPair='all', depth='50')
 |      Returns the order book for a given market, as well as a sequence
 |      number for use with the Push API and an indicator specifying whether
 |      the market is frozen. You may set currencyPair to "all" to get the
 |      order books of all markets.
 |
 |  returnTicker(self)
 |      Returns the ticker for all markets.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from PoloniexPublic:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [6]:
from poloniex import Poloniex
polo = Poloniex()
ticker = polo.returnTicker()['USDT_BTC']
print(ticker)

{'id': 121, 'last': 3988.98638566, 'lowestAsk': 3993.53394256, 'highestBid': 3988.98638575, 'percentChange': -4.853e-05, 'baseVolume': 852486.51488815, 'quoteVolume': 213.29721932, 'isFrozen': 0, 'high24hr': 4018.16171549, 'low24hr': 3977.24173274}

In [7]:
volume = polo.return24hVolume()['BTC_BCN']
volume

{'BTC': 2.63095072, 'BCN': 14328586.43942021}

In [13]:
#TIME CONVERSION to UNIX TIME
import time
import datetime
startdate= '1/11/2017'
enddate = '31/12/2018'

startdate = datetime.datetime.strptime(startdate, "%d/%m/%Y").timestamp()
enddate = datetime.datetime.strptime(enddate, "%d/%m/%Y").timestamp()
startdate

1509512400.0

In [9]:
#pull HISTORICAL DATA
#86400 denotes daily
import pandas as pd
Daily_data =polo.returnChartData('USDT_BTC', 86400, start= startdate, end= enddate)
Daily_data = pd.DataFrame(Daily_data)
Daily_data['True Date']= pd.to_datetime(Daily_data['date'], unit='s')
#moving average columns
Daily_data['MA10'] = Daily_data['close'].rolling(10).mean()
Daily_data['MA20'] = Daily_data['close'].rolling(20).mean()
Daily_data['MA50'] = Daily_data['close'].rolling(50).mean()
Daily_data

,close,date,high,low,open,quoteVolume,volume,weightedAverage,True Date,MA10,MA20,MA50
0,6739.791199,1509512400,6739.791199,6739.791199,6739.791199,0.000000,0.000000e+00,6739.791199,2017-11-01 05:00:00,NaN,NaN,NaN
1,7025.000000,1509580800,7281.428000,6607.302968,6739.791199,10748.349664,7.440179e+07,6922.159330,2017-11-02 00:00:00,NaN,NaN,NaN
2,7124.360000,1509667200,7438.629201,6921.239237,7025.000000,5919.592505,4.260343e+07,7197.020867,2017-11-03 00:00:00,NaN,NaN,NaN
3,7366.000000,1509753600,7440.000000,6864.163065,7124.360000,5099.928687,3.676271e+07,7208.474831,2017-11-04 00:00:00,NaN,NaN,NaN
4,7379.168137,1509840000,7599.000000,7250.300000,7360.000000,4322.230529,3.223164e+07,7457.176840,2017-11-05 00:00:00,NaN,NaN,NaN
5,6929.970421,1509926400,7420.000000,6908.513159,7379.168137,6588.708814,4.709258e+07,7147.466779,2017-11-06 00:00:00,NaN,NaN,NaN
6,7084.873445,1510012800,7251.000000,6929.970421,6929.970421,4117.554845,2.911407e+07,7070.717169,2017-11-07 00:00:00,NaN,NaN,NaN
7,7410.000000,1510099200,7770.999300,7000.000000,7084.873445,9304.062112,6.844777e+07,7356.761860,2017-11-08 00:00:00,NaN,NaN,NaN
8,7020.000000,1510185600,7442.000000,6955.479466,7398.000000,6184.854345,4.456109e+07,7204.873655,2017-11-09 00:00:00,NaN,NaN,NaN
9,6543.204218,1510272000,7277.392000,6315.000000,7020.000000,13449.766337,9.082739e+07,6753.083426,2017-11-10 00:00:00,7062.236742,NaN,NaN
10,6300.000000,1510358400,6800.000000,6150.000000,6544.440400,12817.548908,8.234972e+07,6424.763427,2017-11-11 00:00:00,7018.257622,NaN,NaN
11,5835.000000,1510444800,6549.000000,5151.000000,6319.000000,28336.758949,1.700409e+08,6000.716945,2017-11-12 00:00:00,6899.257622,NaN,NaN
12,6475.778637,1510531200,6701.985325,5773.222563,5840.545884,18072.319344,1.136491e+08,6288.574394,2017-11-13 00:00:00,6834.399486,NaN,NaN
13,6554.918265,1510617600,6688.000000,6299.358928,6478.000000,6785.763522,4.431548e+07,6530.654291,2017-11-14 00:00:00,6753.291312,NaN,NaN
14,7275.119200,1510704000,7298.350000,6554.918265,6554.918265,9572.663969,6.712821e+07,7012.490430,2017-11-15 00:00:00,6742.886418,NaN,NaN
15,7858.001000,1510790400,7980.000000,7082.128623,7275.119200,11103.863067,8.362667e+07,7531.313214,2017-11-16 00:00:00,6835.689476,NaN,NaN
16,7687.510115,1510876800,8022.000000,7511.000000,7858.999000,8946.190523,6.982431e+07,7804.921515,2017-11-17 00:00:00,6895.953143,NaN,NaN
17,7770.000000,1510963200,7855.180018,7413.000000,7687.510115,5862.046776,4.481716e+07,7645.308905,2017-11-18 00:00:00,6931.953143,NaN,NaN
18,8060.000000,1511049600,8131.298873,7650.000000,7768.383431,5244.926356,4.146213e+07,7905.188094,2017-11-19 00:00:00,7035.953143,NaN,NaN
19,8249.000000,1511136000,8299.754000,7951.000000,8076.499667,4201.593710,3.428028e+07,8158.875739,2017-11-20 00:00:00,7206.532722,7134.384732,NaN
20,8107.000000,1511222400,8389.167000,7807.000000,8249.000000,8320.613593,6.739400e+07,8099.642749,2017-11-21 00:00:00,7387.232722,7202.745172,NaN
21,8213.645565,1511308800,8319.000000,8077.824403,8107.000000,4371.911811,3.587110e+07,8204.900224,2017-11-22 00:00:00,7625.097278,7262.177450,NaN
22,8000.000000,1511395200,8268.314000,8000.000000,8213.645565,5505.679173,4.492607e+07,8159.951226,2017-11-23 00:00:00,7777.519414,7305.959450,NaN
23,8198.930000,1511481600,8338.580613,7890.000000,8000.000000,7086.676336,5.772680e+07,8145.820942,2017-11-24 00:00:00,7941.920588,7347.605950,NaN
24,8709.000000,1511568000,8709.999999,8144.523625,8190.000500,6589.407387,5.575375e+07,8461.117863,2017-11-25 00:00:00,8085.308668,7414.097543,NaN
25,9284.336588,1511654400,9350.000000,8683.000000,8709.000000,7658.582138,6.911687e+07,9024.761071,2017-11-26 00:00:00,8227.942227,7531.815852,NaN
26,9711.000000,1511740800,9730.000000,9211.000000,9284.336588,8362.805446,7.974310e+07,9535.448142,2017-11-27 00:00:00,8430.291215,7663.122179,NaN
27,9879.968759,1511827200,9951.427662,9600.000000,9711.000000,6232.037644,6.124682e+07,9827.735174,2017-11-28 00:00:00,8641.288091,7786.620617,NaN
28,9702.000000,1511913600,11447.095532,8700.000000,9882.098660,25162.035402,2.556944e+08,10161.911082,2017-11-29 00:00:00,8805.488091,7920.720617,NaN
29,9907.676820,1512000000,10570.100000,8861.000000,9731.000000,14375.626593,1.390911e+08,9675.478906,2017-11-30 00:00:00,8971.355773,8088.944247,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
396,4162.648713,1543708800,4311.320445,4105.000000,4206.800000,1426.211530,5.970465e+06,4186.241015,2018-12-02 00:00:00,4114.148567,4736.240905,5799.931782
397,3890.351510,1543795200,4174.441466,3825.798050,4162.905710,1544.680618,6.132439e+06,3970.037151,2018-12-03 00:00:00,4061.083718,4607.375627,5750.891373
398,3955.574290,1543881600,4079.000000,3772.635231,3890.351510,1094.253559,4.297561e+06,3927.390151,2018-12-04 00:00:00,4063.323509,4509.682988,5695.002859
399,3769.809744,1543968000,3971.073210,3745.000000,3955.504280,1486.151023,5.735792e+06,3859.495009,2018-12-05 00:00:00,4030.210647,4410.933587,5635.223955
400,3508.715290,1544054400,3887.965300,3498.768873,3766.015480,2521.571855,9.334594e+06,3701.894764,2018-12-06 00:00:00,3996.060082,4303.934940,5570.603256
401,3401.586952,1544140800,3530.000000,3227.020000,3502.326894,3856.746777,1.309998e+07,3396.640231,2018-12-07 00:00:00,3948.213706,4192.494760,5506.434995
402,3409.251003,1544227200,3494.379436,3280.764140,3401.276245,1858.397428,6.296904e+06,3388.351576,2018-12-08 00:00:00,3862.294570,4079.990553,5444.057274
403,3549.010830,1544313600,3655.937074,3396.375833,3407.031900,1580.354079,5.570751e+06,3525.002067,2018-12-09 00:00:00,3788.087263,4011.163760,5383.178734
404,3441.270000,1544400000,3610.000000,3382.605500,3549.010830,1430.077045,4.965297e+06,3472.048597,2018-12-10 00:00:00,3728.127913,3954.709747,5320.159218
405,3380.000000,1544486400,3459.266200,3320.959900,3438.251480,1114.090701,3.776573e+06,3389.825467,2018-12-11 00:00:00,3646.821833,3890.359747,5256.128121
406,3445.920090,1544572800,3487.755654,3358.060500,3380.709370,1047.455951,3.584454e+06,3422.056792,2018-12-12 00:00:00,3575.148971,3844.648769,5193.923434
407,3301.056640,1544659200,3456.429715,3252.110000,3450.372820,1161.182347,3.905307e+06,3363.216212,2018-12-13 00:00:00,3516.219484,3788.651601,5128.715087
408,3221.657197,1544745600,3339.980000,3180.000000,3301.056640,1163.596727,3.774999e+06,3244.250065,2018-12-14 00:00:00,3442.827775,3753.075642,5062.368231
409,3216.144738,1544832000,3263.900000,3157.766310,3221.326800,902.037930,2.893066e+06,3207.255141,2018-12-15 00:00:00,3387.461274,3708.835961,4995.891126
410,3223.744766,1544918400,3292.528170,3208.192118,3212.089357,533.521675,1.734325e+06,3250.711051,2018-12-16 00:00:00,3358.964222,3677.512152,4930.320381
411,3505.398270,1545004800,3590.000000,3221.000000,3225.034780,1653.402705,5.685567e+06,3438.706429,2018-12-17 00:00:00,3369.345354,3658.779530,4870.528346
412,3650.806981,1545091200,3676.116900,3438.997576,3507.224760,1375.281461,4.866016e+06,3538.196634,2018-12-18 00:00:00,3393.500951,3627.897760,4816.544486
413,3667.664189,1545177600,3918.056658,3625.402690,3652.267304,2912.823252,1.091057e+07,3745.704225,2018-12-19 00:00:00,3405.366287,3596.726775,4763.253049
414,4050.654950,1545264000,4118.000000,3642.617800,3664.465200,2673.048971,1.058288e+07,3959.106292,2018-12-20 00:00:00,3466.304782,3597.216348,4716.740110
415,3836.540057,1545350400,4145.280459,3766.650260,4050.000000,1783.377255,7.036138e+06,3945.400960,2018-12-21 00:00:00,3511.958788,3579.390311,4665.365569
416,3948.864441,1545436800,3974.263900,3788.735010,3838.873149,1362.975818,5.252760e+06,3853.890982,2018-12-22 00:00:00,3562.253223,3568.701097,4615.634706
417,3929.100000,1545523200,4020.000000,3875.954400,3948.864441,1038.881367,4.109962e+06,3956.142167,2018-12-23 00:00:00,3625.057559,3570.638521,4566.474708
418,4010.268128,1545609600,4200.000000,3929.887825,3929.887825,2208.813764,9.043261e+06,4094.170732,2018-12-24 00:00:00,3703.918652,3573.373213,4517.040071
419,3740.678415,1545696000,4021.320940,3650.900000,4010.268128,1602.203079,6.002744e+06,3746.556457,2018-12-25 00:00:00,3756.372020,3571.916647,4462.425866
420,3779.911200,1545782400,3839.000000,3654.987680,3740.990410,1009.082700,3.776287e+06,3742.297023,2018-12-26 00:00:00,3811.988663,3585.476442,4407.648643
421,3565.271144,1545868800,3818.043221,3535.000000,3780.106690,1152.783064,4.238918e+06,3677.117249,2018-12-27 00:00:00,3817.975951,3593.660652,4347.446066
422,3840.411604,1545955200,3890.000000,3543.312729,3565.271144,1458.652548,5.459147e+06,3742.596186,2018-12-28 00:00:00,3836.936413,3615.218682,4294.649730
423,3691.749815,1546041600,3889.100000,3672.110000,3833.356940,1121.507538,4.275756e+06,3812.507524,2018-12-29 00:00:00,3839.344975,3622.355631,4240.090726
424,3798.240000,1546128000,3820.000000,3658.599971,3693.703230,477.113218,1.794571e+06,3761.310672,2018-12-30 00:00:00,3814.103480,3640.204131,4187.307066
425,3696.222300,1546214400,3809.090500,3642.000000,3798.970000,405.715129,1.515006e+06,3734.161163,2018-12-31 00:00:00,3800.071705,3656.015246,4132.085453

In [10]:
#REVERSE DATESTAMP COVERSION
import os, datetime
ts = int("1546327800")

#datetime.datetime.fromtimestamp(float(os.path.getmtime(1546383600))).strftime("%B %d, %Y")
time.strftime("%a %d %b %Y GMT", time.gmtime(1553144400.0))

'Thu 21 Mar 2019 GMT'

In [11]:
#Create separate Datframe for SMA analysis
sma_strategy = Daily_data[['True Date','close','MA10','MA20','MA50']].copy()

sma_strategy

              True Date        close         MA10         MA20         MA50
0   2017-11-01 05:00:00  6739.791199          NaN          NaN          NaN
1   2017-11-02 00:00:00  7025.000000          NaN          NaN          NaN
2   2017-11-03 00:00:00  7124.360000          NaN          NaN          NaN
3   2017-11-04 00:00:00  7366.000000          NaN          NaN          NaN
4   2017-11-05 00:00:00  7379.168137          NaN          NaN          NaN
5   2017-11-06 00:00:00  6929.970421          NaN          NaN          NaN
6   2017-11-07 00:00:00  7084.873445          NaN          NaN          NaN
7   2017-11-08 00:00:00  7410.000000          NaN          NaN          NaN
8   2017-11-09 00:00:00  7020.000000          NaN          NaN          NaN
9   2017-11-10 00:00:00  6543.204218  7062.236742          NaN          NaN
10  2017-11-11 00:00:00  6300.000000  7018.257622          NaN          NaN
11  2017-11-12 00:00:00  5835.000000  6899.257622          NaN          NaN
12  2017-11-13 00:00:00  6475.778637  6834.399486          NaN          NaN
13  2017-11-14 00:00:00  6554.918265  6753.291312          NaN          NaN
14  2017-11-15 00:00:00  7275.119200  6742.886418          NaN          NaN
15  2017-11-16 00:00:00  7858.001000  6835.689476          NaN          NaN
16  2017-11-17 00:00:00  7687.510115  6895.953143          NaN          NaN
17  2017-11-18 00:00:00  7770.000000  6931.953143          NaN          NaN
18  2017-11-19 00:00:00  8060.000000  7035.953143          NaN          NaN
19  2017-11-20 00:00:00  8249.000000  7206.532722  7134.384732          NaN
20  2017-11-21 00:00:00  8107.000000  7387.232722  7202.745172          NaN
21  2017-11-22 00:00:00  8213.645565  7625.097278  7262.177450          NaN
22  2017-11-23 00:00:00  8000.000000  7777.519414  7305.959450          NaN
23  2017-11-24 00:00:00  8198.930000  7941.920588  7347.605950          NaN
24  2017-11-25 00:00:00  8709.000000  8085.308668  7414.097543          NaN
25  2017-11-26 00:00:00  9284.336588  8227.942227  7531.815852          NaN
26  2017-11-27 00:00:00  9711.000000  8430.291215  7663.122179          NaN
27  2017-11-28 00:00:00  9879.968759  8641.288091  7786.620617          NaN
28  2017-11-29 00:00:00  9702.000000  8805.488091  7920.720617          NaN
29  2017-11-30 00:00:00  9907.676820  8971.355773  8088.944247          NaN
..                  ...          ...          ...          ...          ...
396 2018-12-02 00:00:00  4162.648713  4114.148567  4736.240905  5799.931782
397 2018-12-03 00:00:00  3890.351510  4061.083718  4607.375627  5750.891373
398 2018-12-04 00:00:00  3955.574290  4063.323509  4509.682988  5695.002859
399 2018-12-05 00:00:00  3769.809744  4030.210647  4410.933587  5635.223955
400 2018-12-06 00:00:00  3508.715290  3996.060082  4303.934940  5570.603256
401 2018-12-07 00:00:00  3401.586952  3948.213706  4192.494760  5506.434995
402 2018-12-08 00:00:00  3409.251003  3862.294570  4079.990553  5444.057274
403 2018-12-09 00:00:00  3549.010830  3788.087263  4011.163760  5383.178734
404 2018-12-10 00:00:00  3441.270000  3728.127913  3954.709747  5320.159218
405 2018-12-11 00:00:00  3380.000000  3646.821833  3890.359747  5256.128121
406 2018-12-12 00:00:00  3445.920090  3575.148971  3844.648769  5193.923434
407 2018-12-13 00:00:00  3301.056640  3516.219484  3788.651601  5128.715087
408 2018-12-14 00:00:00  3221.657197  3442.827775  3753.075642  5062.368231
409 2018-12-15 00:00:00  3216.144738  3387.461274  3708.835961  4995.891126
410 2018-12-16 00:00:00  3223.744766  3358.964222  3677.512152  4930.320381
411 2018-12-17 00:00:00  3505.398270  3369.345354  3658.779530  4870.528346
412 2018-12-18 00:00:00  3650.806981  3393.500951  3627.897760  4816.544486
413 2018-12-19 00:00:00  3667.664189  3405.366287  3596.726775  4763.253049
414 2018-12-20 00:00:00  4050.654950  3466.304782  3597.216348  4716.740110
415 2018-12-21 00:00:00  3836.540057  3511.958788  3579.390311  4665.365569
416 2018-12-22 00:00:00  3948.864441  3562.253223  3568.701097  4615.634706
417 2018-12-23 00:00:00  3929.100000  3625.057559  3570.638521  4566.474708
418 2018-12-24 00:00:00  4010.268128  3703.918652  3573.373213  4517.040071
419 2018-12-25 00:00:00  3740.678415  3756.372020  3571.916647  4462.425866
420 2018-12-26 00:00:00  3779.911200  3811.988663  3585.476442  4407.648643
421 2018-12-27 00:00:00  3565.271144  3817.975951  3593.660652  4347.446066
422 2018-12-28 00:00:00  3840.411604  3836.936413  3615.218682  4294.649730
423 2018-12-29 00:00:00  3691.749815  3839.344975  3622.355631  4240.090726
424 2018-12-30 00:00:00  3798.240000  3814.103480  3640.204131  4187.307066
425 2018-12-31 00:00:00  3696.222300  3800.071705  3656.015246  4132.085453

[426 rows x 5 columns]

In [12]:
#sma_strategy['True Date'] = pd.DatetimeIndex(sma_strategy['True Date']).date


#sma_strategy = sma_strategy.set_index(['True Date'])

#sma_strategy.loc['2018-1-1':'2018-12-31']

sma_strategy.head()
#sma_strategy['True Date'][0].year
sma_strategy[sma_strategy['True Date'].year == '2017']

AttributeError: 'Series' object has no attribute 'year'